# https://gist.github.com/gnarf/b103e77f37236ca72d8e
:vms:
  master:
    :hostname: "master"
    # :ip: "10.0.0.10"
    :ip: "192.168.50.101"
    :ram: 2048
    :cpu: 2
    :box: "ubuntu/xenial64"
    :id: 10

  worker1:
    :hostname: "worker1"
    # :ip: "10.0.0.11"
    :ip: "192.168.50.102"
    :ram: 2048
    :cpu: 2
    :box: "ubuntu/xenial64"
    :id: 11

  worker2:
    :hostname: "worker2"
    # :ip: "10.0.0.12"
    :ip: "192.168.50.103"
    :ram: 2048
    :cpu: 2
    :box: "ubuntu/xenial64"
    :id: 12

  # worker3:
  #   :hostname: "worker3"
  #   # :ip: "10.0.0.13"
  #   :ip: "192.168.50.104"
  #   :ram: 1024
  #   :cpu: 2
  #   :box: "ubuntu/xenial64"
  #   :id: 13

:groups:
  master:
    - master
  slaves:
    - worker1
    - worker2
    # - worker3
  agents:
    - worker1
    - worker2
    # - worker3
  servers:
    - master
    - worker1
    - worker2
    # - worker3
  kubernetes-master:
    - master
  kubernetes-workers:
    - worker1
    - worker2
    # - worker3
  kubernetes:
    - master
    - worker1
    - worker2
    # - worker3
