---
- name: Check current docker-compose version.
  command: docker-compose --version
  register: boss__kubernetes__kubeadm__compose_current_version
  changed_when: false
  failed_when: false

- name: Delete existing docker-compose version if it's different.
  file:
    path: "{{ boss__kubernetes__kubeadm__compose_path }}"
    state: absent
  when: >
    boss__kubernetes__kubeadm__compose_current_version.stdout is defined
    and boss__kubernetes__kubeadm__compose_version not in boss__kubernetes__kubeadm__compose_current_version.stdout

- name: Install Docker Compose (if configured).
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ boss__kubernetes__kubeadm__compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ boss__kubernetes__kubeadm__compose_path }}"
    mode: 0755
  when: ansible_architecture is match("x86_64")

- name: Remove docker-compose (if configured).
  apt:
    name: "docker-compose"
    state: "absent"
  when: ansible_architecture is not match("x86_64")

- name: Remove docker-compose (if configured).
  apt:
    name: "python-pip"
    state: "present"
  when: ansible_architecture is not match("x86_64")

# sudo apt-get remove docker-compose
# sudo apt-get install python-pip
# sudo pip install docker-compose
# https://github.com/hypriot/arm-compose/issues/15
- name: Ensure pip_install_packages are installed.
  pip:
    name: "docker-compose"
    version: "{{ boss__kubernetes__kubeadm__compose_version }}"
    state: "present"
    # executable: "{{ 'pip3' if pip_package == 'python3-pip' else 'pip' }}"
  when: ansible_architecture is not match("x86_64")
