---
# SOURCE: https://github.com/chrisruffalo/ansible-gluster/blob/44a082f34a56dc22c439fc3a60a5fa3b2460565d/roles/gluster-server/tasks/facts.yml
- block:
  - name: Set system architecture for AMD64/x86_64
    set_fact:
      sys_arch: "amd64"
    when: ansible_architecture is match("x86_64") or (ansible_architecture | lower) is match("amd64")

  - name: Set system architecture for i386/x86
    set_fact:
      sys_arch: "386"
    when: ansible_architecture is match("i386")

  - name: Set system architecture for ARM64
    set_fact:
      sys_arch: "arm64"
    when: ansible_architecture is match("arm64")

  - name: Set system architecture for ARMv7
    set_fact:
      sys_arch: "armv7"
    when: ansible_architecture is match("armv7.+")

  - name: Set system architecture for ARMv6
    set_fact:
      sys_arch: "armv6"
    when: ansible_architecture is match("armv6.+")

  - name: Set system architecture for ARMv5
    set_fact:
      sys_arch: "armv5"
    when: ansible_architecture is match("armv5.+")

  - name: Set system architecture for ansible var boss__kubernetes__kubeadm__apt_arch
    set_fact:
      boss__kubernetes__kubeadm__apt_arch: "{{sys_arch}}"


# Taken from decide_master_name.yml
- block:
  - name: by default set master name to inventory definition (no MasterHA case)
    set_fact: master_name={{ groups['primary-master'][0] }}
    when:
    - not custom.networking.fqdn.always
    - not custom.networking.fqdn.master
    - groups['masters'] | length == 1

  - name: force use fqdn for master name (no MasterHA case)
    set_fact: master_name={{ hostvars[groups['primary-master'][0]]['ansible_fqdn'] }}
    when:
    - custom.networking.fqdn.always or custom.networking.fqdn.master
    - groups['masters'] | length == 1

  - name: force use fqdn for master name (MasterHA case)
    set_fact: master_name={{ custom.networking.masterha_fqdn }}
    when:
    - custom.networking.fqdn.always or custom.networking.fqdn.master
    - groups['masters'] | length > 1

  - name: force use vip for master name (MasterHA case)
    set_fact: master_name={{ custom.networking.masterha_vip }}
    when:
    - not custom.networking.fqdn.always
    - not custom.networking.fqdn.master
    - groups['masters'] | length > 1

  tags:
  - always