---
- include_tasks: facts.yml

- include_tasks: prepare.yml
  when: boss__kubernetes__kubeadm__run_prepare


- include_tasks: master.yml
  when: boss__kubernetes__kubeadm__run_master

- include_tasks: nodes.yml
  when: boss__kubernetes__kubeadm__run_nodes
