---

###########################################################################
# GRAB JOIN COMMAND FROM MASTER!!!!!!!!!!!!!!!!!!!!!!!!!!!!
###########################################################################

### Generate a token&hash on master and use them
- block:
  - set_fact:
      env_kc: '{{ proxy_env |default({}) | combine ({"PATH" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"  }) | combine ({"KUBECONFIG" :"/etc/kubernetes/admin.conf"}) }}'

  - name: get join command from master node, and set fact on workers
    shell: cat /etc/kubeadm-join.sh
    environment: '{{env_kc}}'
    # environment -> is required due to a k8s bug which makes kubeadm need internet to generate a token. setting version is not allowed
    # Optionally using "--config /etc/kubernetes/kubeadm-master.conf" to get rid of the message that it tries to connect to internet for version
    register: kubeadm_token_whash_n
    delegate_to: "{{groups['primary-master'][0]}}"
    run_once: yes
    # when:
    # - InitConfiguration is not defined or InitConfiguration.bootstrapTokens is not defined or InitConfiguration.bootstrapTokens[0].token is not defined
    changed_when: false


  - name: 'Display registered value kubeadm_token_whash_n.stdout_lines[0]'
    debug:
      var: kubeadm_token_whash_n.stdout_lines[0]
    changed_when: false
    tags:
    - cluster_status

# TEMPORARY DISABLED
- name: kubeadm_join
  set_fact:
    kubeadm_join: "{{kubeadm_token_whash_n.stdout_lines[0]}}"
  # when: inventory_hostname == master_hostname


- name: join nodes
  shell: >
     systemctl stop kubelet ; kubeadm reset --force ;
     echo "{{kubeadm_join}}" > /etc/kubeadm-join.sh ;
     cat /etc/kubeadm-join.sh ;
     bash /etc/kubeadm-join.sh ;
  args:
    creates: /etc/kubeadm-join.sh

- name: checking all nodes up
  shell: >
      export KUBECONFIG=/etc/kubernetes/admin.conf ;
      kubectl get nodes {{item}}
  register: result
  environment: '{{env_kc}}'
  until: result.stdout.find("Ready") != -1
  delegate_to: "{{groups['primary-master'][0]}}"
  retries: 100
  delay: 10
  with_items: "{{ groups['nodes'] }}"
  when: inventory_hostname == master_hostname
