########################################################
#post_cluster_deploy.yml
########################################################
---
- set_fact:
    env_kc: '{{ proxy_env |default({}) | combine ({"KUBECONFIG" :"/etc/kubernetes/admin.conf"}) }}'
  tags:
  - always

- name: Install boss__kubernetes__kubeadm__k8s_addons_urls (with proxy)
  command: /usr/bin/kubectl apply -f {{ item }}
  with_items: "{{ boss__kubernetes__kubeadm__k8s_addons_urls | default ('') }}"
  environment: '{{env_kc}}'
  when: boss__kubernetes__kubeadm__k8s_addons_urls is defined
  tags:
  - k8s_addons
