########################################################
# taints.yml
########################################################

---
- name: apply boss__kubernetes__kubeadm__taints_master
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: 'kubectl taint nodes {{ inventory_hostname_short }} {{ item }} --overwrite'
  when: boss__kubernetes__kubeadm__taints_master is defined
  with_items: '{{ boss__kubernetes__kubeadm__taints_master }}'
  tags:
  - taints

- name: apply boss__kubernetes__kubeadm__master_uncordon
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: 'kubectl uncordon {{ inventory_hostname_short }} '
  when: boss__kubernetes__kubeadm__master_uncordon is defined
  tags:
  - taints

- name: 'Wait few seconds for taints/uncordon on master take effect'
  pause: seconds=3
  when: boss__kubernetes__kubeadm__taints_master is defined or boss__kubernetes__kubeadm__master_uncordon is defined
  tags:
  - taints
