####################################################
# - include_tasks: modules.yml
####################################################

- name: Enable required kernel modules via modprobe
  modprobe:
    name: "{{item}}"
    state: present
  with_items:
  - ip_vs
  - ip_vs_rr
  - ip_vs_wrr
  - ip_vs_sh
  - nf_conntrack_ipv4

# FIXME: We might not need this!!
- name: Add kernel modules to /etc/modules required kernel modules via modprobe. NOTE WE MIGHT NOT NEED THIS
  lineinfile:
    path: /etc/modules
    line: '{{item}}'
    create: yes
    state: present
  with_items:
  - ip_vs
  - ip_vs_rr
  - ip_vs_wrr
  - ip_vs_sh
  - nf_conntrack_ipv4


- name: net.bridge.bridge-nf-call-ip6tables=1
  sysctl: name=net.bridge.bridge-nf-call-ip6tables value=1 state=present reload=yes sysctl_set=yes

- name: net.bridge.bridge-nf-call-iptables=1
  sysctl: name=net.bridge.bridge-nf-call-iptables value=1 state=present reload=yes sysctl_set=yes
