####################################################
# - include_tasks: modules.yml
####################################################

- name: Enable required kernel modules via modprobe
  modprobe:
    name: "{{item}}"
    state: present
  with_items:
  - ip_vs
  - ip_vs_rr
  - ip_vs_wrr
  - ip_vs_sh
  - nf_conntrack_ipv4

# FIXME: We might not need this!!
- name: Add kernel modules to /etc/modules required kernel modules via modprobe. NOTE WE MIGHT NOT NEED THIS
  lineinfile:
    path: /etc/modules
    line: '{{item}}'
    create: yes
    state: present
  with_items:
  - ip_vs
  - ip_vs_rr
  - ip_vs_wrr
  - ip_vs_sh
  - nf_conntrack_ipv4


####################################################
# - include_tasks: install.yml
####################################################

- name: add the kubernetes apt repo key
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present

- name: add the kubernetes apt repo
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-{{ansible_distribution_release}} main"
    update_cache: True
    state: present

- name: Install k8 dependencies
  apt:
    name: "{{ item }}"
    update_cache: True
  with_items:
  - apt-transport-https

- name: install kubernetes
  apt: name={{ item }} state=present allow_unauthenticated=yes
  with_items:
    # - docker.io
    - kubelet
    - kubeadm
    - kubectl
    - ntp


####################################################
# - include_tasks: configure.yml
####################################################

- name: net.ipv4.ip_forward=1
  sysctl: name=net.ipv4.ip_forward value=1 state=present reload=yes sysctl_set=yes

- service: name=ntp state=started enabled=yes

- service: name=kubelet state=started enabled=yes
